video-player:
  exe: 'mpv'
  pre-url-flags: '--fs'
  ipc:
    exe-suffix-socket-location: '--input-ipc-server=/tmp/mpvsocket'
    pause:  '{"command": ["cycle", "pause"]}'
    play: '{"command": ["cycle", "pause"]}'