video-player:
  exe: 'mpv'
  pre-url-flags: '--fs'
  ipc:
    socket-flag: '--input-ipc-server='
    socket-path: '/tmp/mpvsocket'
    pause:  '{"command": ["cycle", "pause"]}'
    play: '{"command": ["cycle", "pause"]}'
    kill: '{"command": ["quit"]}'