video-player:
  exe: 'mpv'
  pre-url-flags: '--fs'
  auto-play: true
  ipc:
    socket-flag: '--input-ipc-server='
    socket-path: '/tmp/mpvsocket'
    pause:  '{"command": ["cycle", "pause"]}'
    play: '{"command": ["cycle", "pause"]}'
    kill: '{"command": ["quit"]}'
    plus15s: '{"command": ["seek" , "+15"]}'
    minus15s: '{"command": ["seek" , "-15"]}'
    templ-addToPlayList: '{"command": ["loadfile" , "@URL@", "append"]}'
    playlist-next: '{"command": ["playlist-next"]}'
    playlist-prev: '{"command": ["playlist-prev"]}'